accounts/urls.py
from django.urls import path

from .views import SignUpView

urlpatterns = [
    path("signup/", SignUpView.as_view(), name="signup"),
]

cookie_stands/urls.py
from django.urls import path
from .views import CookieStandList, CookieStandDetail

urlpatterns = [
    path("", CookieStandList.as_view(), name="Cookie_list"),
    path("<int:pk>/", CookieStandDetail.as_view(), name="Cookie_detail"),
]

project/urls.py
from django.contrib import admin
from django.urls import include, path
from rest_framework_simplejwt import views as jwt_views
from .views import MyTokenObtainPairView
from django.views.generic.base import TemplateView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("api/v1/cookie_stands/", include("cookie_stands.urls")),
    path("api-auth/", include("rest_framework.urls")),
    path(
        "api/token/",
        MyTokenObtainPairView.as_view(),
        name="token_obtain_pair",
    ),
    path(
        "api/token/refresh/",
        jwt_views.TokenRefreshView.as_view(),
        name="token_refresh",
    ),
    path("cookie_stands/", include("cookie_stands.urls_front")),
    path("", TemplateView.as_view(template_name="home.html"), name="home"),
    path("about/", TemplateView.as_view(template_name="about.html"), name="about"),
    path("accounts/", include("accounts.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
]

accounts/models.py
from django.contrib.auth.models import AbstractUser


class CustomUser(AbstractUser):
    pass
    # add additional fields in here

    def __str__(self):
        return self.username

cookie_stands/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.urls import reverse


class CookieStand(models.Model):
    location = models.CharField(max_length=256)
    owner = models.ForeignKey(
        get_user_model(), on_delete=models.CASCADE, null=True, blank=True
    )
    description = models.TextField(blank=True)
    hourly_sales = models.JSONField(default=list, null=True)
    minimum_customers_per_hour = models.IntegerField(default=0)
    maximum_customers_per_hour = models.IntegerField(default=0)
    average_cookies_per_sale = models.FloatField(default=0)

    def __str__(self):
        return self.location

    def get_absolute_url(self):
        return reverse('Cookie_detail', args=[str(self.owner)])

    # cheak the reverse

things/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.urls import reverse


class Thing(models.Model):
    name = models.CharField(max_length=256)
    rating = models.IntegerField(default=0, blank=True)
    reviewer = models.ForeignKey(
        get_user_model(), on_delete=models.CASCADE, null=True, blank=True
    )
    description = models.TextField(default="", null=True, blank=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('thing_detail', args=[str(self.id)])

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ("username", "email")


class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = CustomUser
        fields = ("username", "email")

accounts/views.py
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView

from .forms import CustomUserCreationForm

class SignUpView(CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy("login")
    template_name = "registration/signup.html"

cookie_stands/views.py
from rest_framework.generics import (
    ListCreateAPIView,
    RetrieveUpdateDestroyAPIView,
)
from .models import CookieStand
from .permissions import IsOwnerOrReadOnly
from .serializers import CookieStandSerializer


class CookieStandList(ListCreateAPIView):
    queryset = CookieStand.objects.all()
    serializer_class = CookieStandSerializer


class CookieStandDetail(RetrieveUpdateDestroyAPIView):
    permission_classes = (IsOwnerOrReadOnly,)
    queryset = CookieStand.objects.all()
    serializer_class = CookieStandSerializer

gamee/views.py
from rest_framework.generics import (
    ListCreateAPIView,
    RetrieveUpdateDestroyAPIView,
)
from .models import CookieStand
from .permissions import IsOwnerOrReadOnly
from .serializers import GameSerializer


class GameList(ListCreateAPIView):
    queryset = CookieStand.objects.all()
    serializer_class = GameSerializer


class GameDetail(RetrieveUpdateDestroyAPIView):
    permission_classes = (IsOwnerOrReadOnly,)
    queryset = CookieStand.objects.all()
    serializer_class = GameSerializer

project/views.py
from rest_framework_simplejwt.serializers import TokenObtainPairSerializer
from rest_framework_simplejwt.views import TokenObtainPairView


class MyTokenObtainPairSerializer(TokenObtainPairSerializer):
    @classmethod
    def get_token(cls, user):
        token = super().get_token(user)

        # Add custom claims
        token["email"] = user.email
        token["username"] = user.username
        # ...

        return token


class MyTokenObtainPairView(TokenObtainPairView):
    serializer_class = MyTokenObtainPairSerializer

templates/CookieStande/CookieStand_create.html
 {% extends 'base.html' %}

{% block content %}


  <div class="w-full max-w-sm p-4 bg-white border border-gray-200 rounded-lg shadow sm:p-6 md:p-8 dark:bg-gray-800 dark:border-gray-700">

    <!-- <form method="post">
      {% csrf_token %}
      {{form.as_p}}
      <input type='submit'/>
    </form> -->
    <form class="space-y-6" method="POST">
      {% csrf_token %}
      <h5 class="text-xl font-medium text-gray-900 dark:text-white">Create a Cookie</h5>
      <div>
        <label for="id_name" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Cookie Name</label>
        <input type="text" name="name" id="id_name"
               class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white"
               placeholder="e.g. celery" required>

      </div>
      <div>
        <label for="id_rating" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Cookie Rating</label>
        <input type="number" name="rating" id="id_rating"
               class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white"
               value="0" min="0" max="5" required>
      </div>
      <div>
        <label for="id_reviewer" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Reviewer</label>
        <select name="reviewer" id="id_reviewer">
          {% for value, choice in form.fields.reviewer.choices %}
            <option value="{{ value }}">{{ choice }}</option>
          {% endfor %}
        </select>
      </div>


      <button type="submit"
              class="w-full text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">
        Create
      </button>
      

    </form>
   </div>

{% endblock content %}

templates/CookieStande/CookieStand_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Cookie</h1>
  <form method="POST">
  {% csrf_token %}
    <p>Do you really want to delete "{{ cookie.name }}"?</p>
    <input type="submit" value="OK">
  </form>
{% endblock content %}
a

templates/CookieStande/CookieStand_list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

  <div class="space-y-8 p-8">

    <h1 class="text-4xl text-center">All the CookieStands</h1>
    <div
      class="w-1/2 mx-auto text-sm font-medium text-gray-900 bg-white border border-gray-200 rounded-lg dark:bg-gray-700 dark:border-gray-600 dark:text-white">

      {% for cookie in CookieStands %}
        <a href="{% url 'Cookie_detail' cookie.pk %}" aria-current="true"
           class="block w-full px-4 py-4 text-white bg-blue-700 border-b border-gray-200 rounded-t-lg cursor-pointer dark:bg-gray-800 dark:border-gray-600">
          {{ cookie.location }}
        </a>
      {% endfor %}
    </div>

  </div>

{% endblock content %}

templates/CookieStande/CookieStand_update.html
{% extends 'base.html' %}

{% block content %}
  {#  <h1>Update cookie</h1>#}
  {#  <form method="POST">#}
  {##}
  {#    {{ form.as_p }}#}
  {#    <input type="submit" value="SAVE">#}
  {#  </form>#}

  <div
    class="w-full max-w-sm p-4 bg-white border border-gray-200 rounded-lg shadow sm:p-6 md:p-8 dark:bg-gray-800 dark:border-gray-700">
    <form class="space-y-6" method="POST">
      {% csrf_token %}
      <h5 class="text-xl font-medium text-gray-900 dark:text-white">Update a cookie</h5>
      <div>
        <label for="id_name" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Name</label>
        <input type="text" name="name" id="id_name"
               class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white"
               required value="{{ cookie.name }}">

      </div>
      <div>
        <label for="id_rating" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Rating</label>
        <input type="number" name="rating" id="id_rating"
               class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white"
               value="{{ cookie.rating }}" min="0" max="5" required>
      </div>
      <div>
        <label for="id_reviewer" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Reviewer</label>
        <select name="reviewer" id="id_reviewer">
          {% for value, choice in form.fields.reviewer.choices %}
            <option value="{{ value }}" {% if value == cookie.reviewer.id %}selected{% endif %}>{{ choice }}</option>
          {% endfor %}
        </select>
      </div>

      <div>
        <label for="id_description"
               class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Description</label>
        <textarea name="description" id="id_description"
                  class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white"
                  placeholder="e.g. Celery gets a bad wrap" required>{{ cookie.description }}</textarea>
      </div>


      <button type="submit"
              class="w-full text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">
        SAVE
      </button>

    </form>
  </div>
{% endblock content %}
<!-- {% extends 'base.html' %}

{% block content %}
  {#  <h1>Update Thing</h1>#}

  <div
    class="w-full max-w-sm p-4 bg-white border border-gray-200 rounded-lg shadow sm:p-6 md:p-8 dark:bg-gray-800 dark:border-gray-700">
    <a href="/cookie_stands/update/{{ cookieStand.pk }}">Update Cookie Stand</a>
<form method="post">
        {% csrf_token %}
        {{form.as_p}}
        <button type='submit'>Update</button>
    </form>
  </div>
{% endblock content %} -->

templates/about.html
{% extends 'base.html' %}

{% block content %}

<div class="w-3/4 mx-auto max-w-sm bg-white border border-gray-200 rounded-lg shadow dark:bg-gray-800 dark:border-gray-700">
    <div class="flex justify-end px-4 pt-4">
        <button id="dropdownButton" data-dropdown-toggle="dropdown" class="inline-block text-gray-500 dark:text-gray-400 hover:bg-gray-100 dark:hover:bg-gray-700 focus:ring-4 focus:outline-none focus:ring-gray-200 dark:focus:ring-gray-700 rounded-lg text-sm p-1.5" type="button">
            <span class="sr-only">Open dropdown</span>
            <svg class="w-6 h-6" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path d="M6 10a2 2 0 11-4 0 2 2 0 014 0zM12 10a2 2 0 11-4 0 2 2 0 014 0zM16 12a2 2 0 100-4 2 2 0 000 4z"></path></svg>
        </button>
        <!-- Dropdown menu -->
        <div id="dropdown" class="z-10 hidden text-base list-none bg-white divide-y divide-gray-100 rounded-lg shadow w-44 dark:bg-gray-700">
            <ul class="py-2" aria-labelledby="dropdownButton">
            <li>
                <a href="#" class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white">Edit</a>
            </li>
            <li>
                <a href="#" class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white">Export Data</a>
            </li>
            <li>
                <a href="#" class="block px-4 py-2 text-sm text-red-600 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white">Delete</a>
            </li>
            </ul>
        </div>
    </div>
    <div class="flex flex-col items-center pb-10 px-4">
        <img class="w-96 h-96 mb-3 rounded-full shadow-lg" src="https://placekeanu.com/200/150" alt="Keanu image"/>
        <h5 class="mb-1 text-xl font-medium text-gray-900 dark:text-white">Not Keanu Reeves</h5>
        <span class="text-sm text-gray-500 dark:text-gray-400">Full Stack Developer</span>
        <div class="flex mt-4 space-x-3 md:mt-6">
            <a href="#" class="inline-flex items-center px-4 py-2 text-sm font-medium text-center text-white bg-blue-700 rounded-lg hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">Add friend</a>
            <a href="#" class="inline-flex items-center px-4 py-2 text-sm font-medium text-center text-gray-900 bg-white border border-gray-300 rounded-lg hover:bg-gray-100 focus:ring-4 focus:outline-none focus:ring-gray-200 dark:bg-gray-800 dark:text-white dark:border-gray-600 dark:hover:bg-gray-700 dark:hover:border-gray-700 dark:focus:ring-gray-700">Message</a>
        </div>
    </div>
</div>

{% endblock content %}

templates/gamee/Game_create.html
{% extends 'base.html' %}

{% block content %}


  <div
    class="w-full max-w-sm p-4 bg-white border border-gray-200 rounded-lg shadow sm:p-6 md:p-8 dark:bg-gray-800 dark:border-gray-700">
    <form class="space-y-6" method="POST">
      {% csrf_token %}
      <h5 class="text-xl font-medium text-gray-900 dark:text-white">Create a Game</h5>
      <div>
        <label for="id_name" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Game Name</label>
        <input type="text" name="name" id="id_name"
               class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white"
               placeholder="e.g. celery" required>

      </div>
      <div>
        <label for="id_rating" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Game Rating</label>
        <input type="number" name="rating" id="id_rating"
               class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white"
               value="0" min="0" max="5" required>
      </div>
      <div>
        <label for="id_reviewer" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Reviewer</label>
        <select name="reviewer" id="id_reviewer">
          {% for value, choice in form.fields.reviewer.choices %}
            <option value="{{ value }}">{{  choice }}</option>
          {% endfor %}
        </select>
      </div>


      <button type="submit"
              class="w-full text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">
        Create
      </button>

    </form>
  </div>

{% endblock content %}

templates/gamee/Game_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Game</h1>
  <form method="POST">
  {% csrf_token %}
    <p>Do you really want to delete "{{ game.name }}"?</p>
    <input type="submit" value="OK">
  </form>
{% endblock content %}

templates/gamee/Game_update.html
{% extends 'base.html' %}

{% block content %}
  {#  <h1>Update Game</h1>#}
  {#  <form method="POST">#}
  {##}
  {#    {{ form.as_p }}#}
  {#    <input type="submit" value="SAVE">#}
  {#  </form>#}

  <div
    class="w-full max-w-sm p-4 bg-white border border-gray-200 rounded-lg shadow sm:p-6 md:p-8 dark:bg-gray-800 dark:border-gray-700">
    <form class="space-y-6" method="POST">
      {% csrf_token %}
      <h5 class="text-xl font-medium text-gray-900 dark:text-white">Update a Game</h5>
      <div>
        <label for="id_name" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Name</label>
        <input type="text" name="name" id="id_name"
               class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white"
               required value="{{ game.name }}">

      </div>
      <div>
        <label for="id_rating" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Rating</label>
        <input type="number" name="rating" id="id_rating"
               class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white"
               value="{{ game.rating }}" min="0" max="5" required>
      </div>
      <div>
        <label for="id_reviewer" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Reviewer</label>
        <select name="reviewer" id="id_reviewer">
          {% for value, choice in form.fields.reviewer.choices %}
            <option value="{{ value }}" {% if value == game.reviewer.id %}selected{% endif %}>{{ choice }}</option>
          {% endfor %}
        </select>
      </div>

      <div>
        <label for="id_description"
               class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Description</label>
        <textarea name="description" id="id_description"
                  class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white"
                  placeholder="e.g. Celery gets a bad wrap" required>{{ game.description }}</textarea>
      </div>


      <button type="submit"
              class="w-full text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">
        SAVE
      </button>

    </form>
  </div>
{% endblock content %}

templates/things/thing_create.html
{% extends 'base.html' %}

{% block content %}


  <div
    class="w-full max-w-sm p-4 bg-white border border-gray-200 rounded-lg shadow sm:p-6 md:p-8 dark:bg-gray-800 dark:border-gray-700">
    <form class="space-y-6" method="POST">
      {% csrf_token %}
      <h5 class="text-xl font-medium text-gray-900 dark:text-white">Create a Thing</h5>
      <div>
        <label for="id_name" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Thing Name</label>
        <input type="text" name="name" id="id_name"
               class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white"
               placeholder="e.g. celery" required>

      </div>
      <div>
        <label for="id_rating" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Thing Rating</label>
        <input type="number" name="rating" id="id_rating"
               class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white"
               value="0" min="0" max="5" required>
      </div>
      <div>
        <label for="id_reviewer" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Reviewer</label>
        <select name="reviewer" id="id_reviewer">
          {% for value, choice in form.fields.reviewer.choices %}
            <option value="{{ value }}">{{  choice }}</option>
          {% endfor %}
        </select>
      </div>


      <button type="submit"
              class="w-full text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">
        Create
      </button>

    </form>
  </div>

{% endblock content %}

templates/things/thing_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Thing</h1>
  <form method="POST">
  {% csrf_token %}
    <p>Do you really want to delete "{{ thing.name }}"?</p>
    <input type="submit" value="OK">
  </form>
{% endblock content %}

templates/things/thing_update.html
{% extends 'base.html' %}

{% block content %}
  {#  <h1>Update Thing</h1>#}
  {#  <form method="POST">#}
  {##}
  {#    {{ form.as_p }}#}
  {#    <input type="submit" value="SAVE">#}
  {#  </form>#}

  <div
    class="w-full max-w-sm p-4 bg-white border border-gray-200 rounded-lg shadow sm:p-6 md:p-8 dark:bg-gray-800 dark:border-gray-700">
    <form class="space-y-6" method="POST">
      {% csrf_token %}
      <h5 class="text-xl font-medium text-gray-900 dark:text-white">Update a Thing</h5>
      <div>
        <label for="id_name" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Name</label>
        <input type="text" name="name" id="id_name"
               class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white"
               required value="{{ thing.name }}">

      </div>
      <div>
        <label for="id_rating" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Rating</label>
        <input type="number" name="rating" id="id_rating"
               class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white"
               value="{{ thing.rating }}" min="0" max="5" required>
      </div>
      <div>
        <label for="id_reviewer" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Reviewer</label>
        <select name="reviewer" id="id_reviewer">
          {% for value, choice in form.fields.reviewer.choices %}
            <option value="{{ value }}" {% if value == thing.reviewer.id %}selected{% endif %}>{{ choice }}</option>
          {% endfor %}
        </select>
      </div>

      <div>
        <label for="id_description"
               class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Description</label>
        <textarea name="description" id="id_description"
                  class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white"
                  placeholder="e.g. Celery gets a bad wrap" required>{{ thing.description }}</textarea>
      </div>


      <button type="submit"
              class="w-full text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">
        SAVE
      </button>

    </form>
  </div>
{% endblock content %}